# frozen_string_literal: true

default: &default

development:
  <<: *default
  llm_provider: 'openai'
  llm_model: 'gpt-4o-mini'

production:
  <<: *default

test:
  <<: *default
  llm_provider: 'deepseek'
  llm_model: 'deepseek-chat'
  deepseek_api_key: 'fake'
